# Generated by Django 4.1.4 on 2023-01-17 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('account_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=45, null=True)),
                ('last_name', models.CharField(blank=True, max_length=45, null=True)),
                ('address', models.CharField(blank=True, max_length=45, null=True)),
                ('phone_number1', models.CharField(max_length=45)),
                ('phone_number2', models.CharField(blank=True, max_length=45, null=True)),
                ('user_name', models.CharField(max_length=45)),
                ('password', models.BinaryField()),
                ('reset_password_token', models.CharField(max_length=45, null=True)),
                ('reset_password_token_expiry', models.DateTimeField(null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile/img')),
            ],
            options={
                'db_table': 'consumer_info',
            },
        ),
        migrations.CreateModel(
            name='Product_Attributes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attribute_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'product_attributes',
            },
        ),
        migrations.CreateModel(
            name='Store_Owner',
            fields=[
                ('account_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=120)),
                ('phone_number1', models.CharField(max_length=45)),
                ('phone_number2', models.CharField(blank=True, max_length=45, null=True)),
                ('user_name', models.CharField(max_length=45)),
                ('password', models.BinaryField()),
                ('reset_password_token', models.CharField(max_length=45, null=True)),
                ('reset_password_token_expiry', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'store_owner_info',
            },
        ),
        migrations.CreateModel(
            name='Store_Info',
            fields=[
                ('store_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=45)),
                ('branch_name', models.CharField(max_length=120)),
                ('store_address1', models.CharField(max_length=120)),
                ('store_address2', models.CharField(max_length=120)),
                ('store_category', models.CharField(max_length=120)),
                ('store_link', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=120)),
                ('email_address', models.CharField(max_length=120)),
                ('profile_pic', models.CharField(default='', max_length=120)),
                ('owner_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='emercado.store_owner')),
            ],
            options={
                'db_table': 'store_info',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=120)),
                ('description', models.TextField(default='')),
                ('product_category', models.TextField()),
                ('has_variation', models.IntegerField(default=0)),
                ('default_image', models.CharField(max_length=120)),
                ('original_price', models.FloatField(default=1)),
                ('available_flag', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('sku', models.CharField(max_length=120)),
                ('status_type', models.IntegerField(default=0)),
                ('store_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='emercado.store_info')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Product_Variations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('option_id', models.TextField()),
                ('attribute_id', models.TextField()),
                ('price', models.FloatField()),
                ('available_flag', models.IntegerField(default=0)),
                ('stocks', models.IntegerField()),
                ('status_type', models.IntegerField(default=0)),
                ('product_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='emercado.products')),
            ],
            options={
                'db_table': 'product_variations',
            },
        ),
        migrations.CreateModel(
            name='Product_Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=45)),
                ('product_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='emercado.products')),
            ],
            options={
                'db_table': 'product_images',
            },
        ),
        migrations.CreateModel(
            name='Product_Attributes_Option',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('option_name', models.CharField(max_length=45)),
                ('attribute_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='emercado.product_attributes')),
            ],
            options={
                'db_table': 'product_attributes_options',
            },
        ),
        migrations.AddField(
            model_name='product_attributes',
            name='product_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='emercado.products'),
        ),
    ]
