# Generated by Django 4.1.5 on 2023-01-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0002_products_weight_store_owner_custom_attributes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_variations',
            name='options_name',
            field=models.TextField(default=''),
        ),
    ]
