# Generated by Django 4.1.5 on 2023-01-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0003_product_variations_options_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_images',
            name='file_name',
            field=models.CharField(max_length=150),
        ),
    ]
