# Generated by Django 4.1.5 on 2023-01-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0004_alter_product_images_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_attributes',
            name='product_id',
            field=models.CharField(default='', max_length=45),
        ),
    ]
