# Generated by Django 4.1.5 on 2023-01-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0005_alter_product_attributes_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_images',
            name='product_id',
            field=models.CharField(default='', max_length=45),
        ),
    ]
