# Generated by Django 4.1.5 on 2023-01-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0007_alter_product_attributes_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_variations',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product_variations',
            name='stocks',
            field=models.IntegerField(default=0),
        ),
    ]
