# Generated by Django 4.1.5 on 2023-01-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0008_alter_product_variations_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_variations',
            name='image',
            field=models.CharField(default='', max_length=120, null=True),
        ),
    ]
