# Generated by Django 4.1.5 on 2023-01-26 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0009_product_variations_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_AddOns',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=150)),
                ('available_flag', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('stocks', models.IntegerField(default=0)),
                ('image', models.CharField(max_length=120, null=True)),
                ('status_type', models.IntegerField(default=0)),
                ('product_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='emercado.products')),
            ],
            options={
                'db_table': 'product_add_ons',
            },
        ),
    ]
