# Generated by Django 4.1.1 on 2023-02-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0011_alter_product_variations_available_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
