# Generated by Django 4.1.5 on 2023-02-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0012_products_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=20)),
                ('account_id', models.CharField(max_length=20)),
                ('store_id', models.CharField(max_length=20)),
                ('date_added', models.DateTimeField()),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='Cart_Key',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=20)),
                ('store_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cart_key',
            },
        ),
    ]
