# Generated by Django 4.1.5 on 2023-02-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0014_cart_addon_id_cart_addon_product_name_cart_cart_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('subtotal', models.FloatField(default=0)),
                ('tax', models.FloatField(default=0)),
                ('shipping_fee', models.FloatField(default=0)),
                ('online_payment_charge', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('items', models.IntegerField(default=0)),
                ('variation', models.CharField(max_length=20, null=True)),
                ('variation_name', models.CharField(max_length=120, null=True)),
                ('addon_id', models.TextField(null=True)),
                ('addon_product_name', models.TextField(null=True)),
                ('account_id', models.CharField(max_length=20)),
                ('store_id', models.CharField(max_length=20)),
                ('order_status', models.CharField(max_length=45)),
                ('date_created', models.DateTimeField()),
                ('date_paid', models.DateTimeField()),
                ('date_compeleted', models.DateTimeField()),
            ],
            options={
                'db_table': 'emcdo_orders',
            },
        ),
        migrations.AlterModelTable(
            name='cart',
            table='emcdo_cart',
        ),
        migrations.AlterModelTable(
            name='cart_key',
            table='emcdo_cart_key',
        ),
        migrations.AlterModelTable(
            name='consumer',
            table='emcdo_consumer_info',
        ),
        migrations.AlterModelTable(
            name='product_addons',
            table='emcdo_product_add_ons',
        ),
        migrations.AlterModelTable(
            name='product_attributes',
            table='emcdo_product_attributes',
        ),
        migrations.AlterModelTable(
            name='product_attributes_option',
            table='emcdo_product_attributes_options',
        ),
        migrations.AlterModelTable(
            name='product_images',
            table='emcdo_product_images',
        ),
        migrations.AlterModelTable(
            name='product_variations',
            table='emcdo_product_variations',
        ),
        migrations.AlterModelTable(
            name='products',
            table='emcdo_products',
        ),
        migrations.AlterModelTable(
            name='store_info',
            table='emcdo_store_info',
        ),
        migrations.AlterModelTable(
            name='store_owner',
            table='emcdo_store_owner_info',
        ),
    ]
