# Generated by Django 4.1.5 on 2023-02-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0015_orders_alter_cart_table_alter_cart_key_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.CharField(default='', max_length=120, null=True),
        ),
    ]
