# Generated by Django 4.1.5 on 2023-02-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0016_cart_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='image',
        ),
    ]
