# Generated by Django 4.1.5 on 2023-02-17 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0017_remove_cart_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='phone_number2',
        ),
    ]
