# Generated by Django 4.1.1 on 2023-02-23 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0018_remove_consumer_phone_number2'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='reset_number_token',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='consumer',
            name='reset_number_token_expiry',
            field=models.DateTimeField(null=True),
        ),
    ]
