# Generated by Django 4.1.6 on 2023-02-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0019_consumer_reset_number_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='date_service',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='date_time_service',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='service_flag',
            field=models.IntegerField(default=0),
        ),
    ]
