# Generated by Django 4.1.1 on 2023-02-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0020_orders_date_service_orders_date_time_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='profile_picture',
            field=models.ImageField(blank=True, default='img/consumer/profile/profile_default.jpg', null=True, upload_to='profile/img'),
        ),
    ]
