# Generated by Django 4.1.5 on 2023-02-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0020_orders_date_service_orders_date_time_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line_Items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=45)),
                ('variation_id', models.CharField(max_length=45)),
                ('add_on_id', models.CharField(max_length=45)),
                ('quantity', models.IntegerField()),
                ('order_id', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'emcdo_line_items',
            },
        ),
        migrations.RemoveField(
            model_name='orders',
            name='addon_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='addon_product_name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='variation',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='variation_name',
        ),
    ]
