# Generated by Django 4.1.5 on 2023-02-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0021_line_items_remove_orders_addon_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='service_instructions',
            field=models.TextField(null=True),
        ),
    ]
