# Generated by Django 4.1.1 on 2023-02-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0022_alter_consumer_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='variation_product_image',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
