# Generated by Django 4.1.1 on 2023-02-24 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0023_cart_variation_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='variation_product_image',
        ),
    ]
