# Generated by Django 4.0.5 on 2023-02-24 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0022_alter_consumer_profile_picture'),
        ('emercado', '0023_alter_cart_account_id'),
    ]

    operations = [
    ]
