# Generated by Django 4.1.1 on 2023-02-24 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0023_alter_cart_account_id'),
        ('emercado', '0024_remove_cart_variation_product_image'),
    ]

    operations = [
    ]
