# Generated by Django 4.1.5 on 2023-02-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0026_orders_service_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line_items',
            name='add_on_id',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='line_items',
            name='variation_id',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
