# Generated by Django 4.1.5 on 2023-02-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0029_alter_cart_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_key',
            name='account_id',
            field=models.CharField(max_length=45),
        ),
    ]
