# Generated by Django 4.1.5 on 2023-02-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0030_alter_cart_key_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='email_address',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='orders',
            name='fullname',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.CharField(default='', max_length=120),
        ),
    ]
