# Generated by Django 4.1.5 on 2023-02-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0031_orders_email_address_orders_fullname_orders_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='account_id',
            field=models.CharField(max_length=120),
        ),
    ]
