# Generated by Django 4.1.5 on 2023-02-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0032_alter_orders_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_image',
            field=models.CharField(default='', max_length=120),
        ),
    ]
