# Generated by Django 4.1.5 on 2023-02-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0034_alter_cart_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_image',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
