# Generated by Django 4.1.5 on 2023-02-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0035_alter_cart_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_available',
            field=models.IntegerField(default=1),
        ),
    ]
