# Generated by Django 4.1.1 on 2023-02-27 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0025_merge_20230224_1712'),
        ('emercado', '0035_alter_cart_product_image'),
    ]

    operations = [
    ]
