# Generated by Django 4.1.5 on 2023-02-27 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0036_merge_20230227_0800'),
        ('emercado', '0036_products_is_available'),
    ]

    operations = [
    ]
