# Generated by Django 4.1.1 on 2023-03-02 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0037_merge_20230227_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='date_compeleted',
            new_name='date_completed',
        ),
    ]
