# Generated by Django 4.1.1 on 2023-03-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0039_orders_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='profile_picture',
            field=models.CharField(default='', max_length=120),
        ),
    ]
