# Generated by Django 4.1.1 on 2023-03-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0040_alter_orders_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant_Owner',
            fields=[
                ('merchant_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('user_name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=120)),
                ('store_address', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=45)),
                ('business_name', models.CharField(max_length=120)),
                ('store_link', models.CharField(max_length=120)),
                ('store_category', models.CharField(max_length=120)),
                ('password', models.BinaryField()),
                ('reset_password_token', models.CharField(max_length=45, null=True)),
                ('reset_password_token_expiry', models.DateTimeField(null=True)),
                ('custom_attributes', models.TextField(default='', null=True)),
                ('custom_category', models.TextField(default='', null=True)),
                ('reset_number_token', models.CharField(max_length=45, null=True)),
                ('reset_number_token_expiry', models.DateTimeField(null=True)),
                ('profile_picture', models.ImageField(blank=True, default='profile_default.jpg', null=True, upload_to='profile/img')),
                ('profile_pic', models.CharField(default='', max_length=120)),
            ],
            options={
                'db_table': 'emcdo_merchant_owner_info',
            },
        ),
    ]
