# Generated by Django 4.1.5 on 2023-03-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0042_alter_merchant_owner_merchant_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Merchant_Owner',
        ),
        migrations.RemoveField(
            model_name='store_info',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='store_info',
            name='first_name',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='store_info',
            name='last_name',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='store_info',
            name='user_name',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.DeleteModel(
            name='Store_Owner',
        ),
    ]
