# Generated by Django 4.1.5 on 2023-03-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0044_alter_cart_id_alter_cart_key_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_info',
            name='password',
            field=models.BinaryField(null=True),
        ),
    ]
