# Generated by Django 4.1.1 on 2023-03-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0045_store_info_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_info',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_default.jpg', null=True, upload_to='profile/img'),
        ),
    ]
