# Generated by Django 4.1.1 on 2023-03-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0046_alter_store_info_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_info',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_default.jpg', null=True, upload_to='profile/img'),
        ),
        migrations.AlterField(
            model_name='store_info',
            name='profile_pic',
            field=models.CharField(default='', max_length=120),
        ),
    ]
