# Generated by Django 4.1.1 on 2023-03-03 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0047_store_info_profile_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store_info',
            old_name='profile_pic',
            new_name='store_pic',
        ),
    ]
