# Generated by Django 4.1.1 on 2023-03-03 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0048_rename_profile_pic_store_info_store_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store_info',
            old_name='store_pic',
            new_name='profile_pic',
        ),
    ]
