# Generated by Django 4.1.5 on 2023-03-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0049_rename_store_pic_store_info_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_info',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
