# Generated by Django 4.1.1 on 2023-03-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0050_store_info_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_info',
            name='reset_number_token',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='store_info',
            name='reset_number_token_expiry',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='store_info',
            name='reset_password_token',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='store_info',
            name='reset_password_token_expiry',
            field=models.DateTimeField(null=True),
        ),
    ]
