# Generated by Django 4.1.5 on 2023-03-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0050_store_info_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='display_flag',
            field=models.IntegerField(default=0),
        ),
    ]
