# Generated by Django 4.1.1 on 2023-03-03 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0051_products_display_flag'),
        ('emercado', '0051_store_info_reset_number_token_and_more'),
    ]

    operations = [
    ]
