# Generated by Django 4.1.5 on 2023-03-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0052_merge_20230303_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
