# Generated by Django 4.1.5 on 2023-03-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0053_cart_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_attributes',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product_attributes_option',
            name='attribute_id',
            field=models.IntegerField(default=0),
        ),
    ]
