# Generated by Django 4.1.1 on 2023-03-07 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0056_alter_product_attributes_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_attributes',
            name='product_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='emercado.products'),
        ),
    ]
