# Generated by Django 4.1.1 on 2023-03-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0057_alter_product_attributes_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_attributes',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
    ]
