# Generated by Django 4.1.1 on 2023-03-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0059_orders_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_code/'),
        ),
    ]
