# Generated by Django 4.1.1 on 2023-03-09 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0061_alter_orders_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line_items',
            name='order_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='emercado.orders'),
        ),
    ]
