# Generated by Django 4.1.1 on 2023-03-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0063_alter_line_items_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='qr_code',
            field=models.ImageField(blank=True, max_length=120, upload_to=''),
        ),
        migrations.AddField(
            model_name='products',
            name='qr_code',
            field=models.ImageField(blank=True, max_length=120, upload_to=''),
        ),
        migrations.AddField(
            model_name='store_info',
            name='qr_code',
            field=models.ImageField(blank=True, max_length=120, upload_to=''),
        ),
    ]
