# Generated by Django 4.1.1 on 2023-03-09 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0059_consumer_id_format_orders_id_format_and_more'),
        ('emercado', '0064_consumer_qr_code_products_qr_code_store_info_qr_code'),
    ]

    operations = [
    ]
