# Generated by Django 4.1.5 on 2023-03-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0066_alter_orders_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='System_User',
            fields=[
                ('account_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_format', models.CharField(max_length=45)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('merchart_access', models.IntegerField(default=0)),
                ('pending_merchant_access', models.IntegerField(default=0)),
                ('approve_merchant_access', models.IntegerField(default=0)),
                ('categories_access', models.IntegerField(default=0)),
                ('user_access', models.IntegerField(default=0)),
                ('add_user_access', models.IntegerField(default=0)),
                ('view_user_access', models.IntegerField(default=0)),
                ('archived_user_access', models.IntegerField(default=0)),
                ('settings_access', models.IntegerField(default=0)),
                ('settings_role_access', models.IntegerField(default=0)),
                ('settings_department_access', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'emcdo_system_user',
            },
        ),
    ]
