# Generated by Django 4.1.5 on 2023-03-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0067_system_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_format', models.CharField(max_length=45)),
                ('role_name', models.CharField(max_length=45)),
                ('dashboard_view_access', models.IntegerField(default=0)),
                ('report_view_access', models.IntegerField(default=0)),
                ('merchant_pending_access', models.IntegerField(default=0)),
                ('merchant_approved_flag', models.IntegerField(default=0)),
                ('merchant_approved_view_access', models.IntegerField(default=0)),
                ('merchant_suspend_access', models.IntegerField(default=0)),
                ('create_merchant_access', models.IntegerField(default=0)),
                ('suspended_access_flag', models.IntegerField(default=0)),
                ('suspended_restore_access', models.IntegerField(default=0)),
                ('suspended_delete_access', models.IntegerField(default=0)),
                ('add_categories_access', models.IntegerField(default=0)),
                ('add_sub_category_access', models.IntegerField(default=0)),
                ('add_user_access', models.IntegerField(default=0)),
                ('user_list_flag', models.IntegerField(default=0)),
                ('edit_user_access', models.IntegerField(default=0)),
                ('archive_user_access', models.IntegerField(default=0)),
                ('archived_user_flag', models.IntegerField(default=0)),
                ('restore_archive_user_access', models.IntegerField(default=0)),
                ('delete_archive_user_access', models.IntegerField(default=0)),
                ('role_flag', models.IntegerField(default=0)),
                ('edit_role_access', models.IntegerField(default=0)),
                ('add_role_access', models.IntegerField(default=0)),
                ('delete_role_access', models.IntegerField(default=0)),
                ('department_flag', models.IntegerField(default=0)),
                ('edit_department_access', models.IntegerField(default=0)),
                ('add_department_acccess', models.IntegerField(default=0)),
                ('delete_department_access', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'emcdo_role',
            },
        ),
        migrations.RemoveField(
            model_name='system_user',
            name='add_user_access',
        ),
        migrations.RemoveField(
            model_name='system_user',
            name='approve_merchant_access',
        ),
        migrations.RemoveField(
            model_name='system_user',
            name='archived_user_access',
        ),
        migrations.RemoveField(
            model_name='system_user',
            name='categories_access',
        ),
        migrations.RemoveField(
            model_name='system_user',
            name='merchart_access',
        ),
        migrations.RemoveField(
            model_name='system_user',
            name='pending_merchant_access',
        ),
        migrations.RemoveField(
            model_name='system_user',
            name='settings_access',
        ),
        migrations.RemoveField(
            model_name='system_user',
            name='settings_department_access',
        ),
        migrations.RemoveField(
            model_name='system_user',
            name='settings_role_access',
        ),
        migrations.RemoveField(
            model_name='system_user',
            name='user_access',
        ),
        migrations.RemoveField(
            model_name='system_user',
            name='view_user_access',
        ),
        migrations.AddField(
            model_name='system_user',
            name='department',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='system_user',
            name='password',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='system_user',
            name='role',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='system_user',
            name='user_name',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='system_user',
            name='email',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='system_user',
            name='first_name',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='system_user',
            name='id_format',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='system_user',
            name='last_name',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='system_user',
            name='phone',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
