# Generated by Django 4.1.5 on 2023-03-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0069_role_display_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_format', models.CharField(max_length=45)),
                ('department_name', models.CharField(max_length=120, null=True)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'emcdo_department',
            },
        ),
    ]
