# Generated by Django 4.1.5 on 2023-03-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0070_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system_user',
            old_name='department',
            new_name='department_id',
        ),
        migrations.RenameField(
            model_name='system_user',
            old_name='role',
            new_name='role_id',
        ),
        migrations.AddField(
            model_name='system_user',
            name='department_name',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='system_user',
            name='role_name',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
