# Generated by Django 4.1.5 on 2023-03-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0071_rename_department_system_user_department_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_user',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
    ]
