# Generated by Django 4.1.5 on 2023-03-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0072_system_user_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='shared_to',
            field=models.TextField(null=True),
        ),
    ]
