# Generated by Django 4.1.1 on 2023-03-17 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0072_system_user_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_info',
            name='store_phone_number',
            field=models.CharField(default='', max_length=120),
        ),
    ]
