# Generated by Django 4.1.5 on 2023-03-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0076_rename_requested_share_order_notifications_requesting_share_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='requesting_name',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
