# Generated by Django 4.1.5 on 2023-03-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0077_notifications_requesting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='images',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
