# Generated by Django 4.1.5 on 2023-03-17 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0078_alter_notifications_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='images',
            new_name='image',
        ),
    ]
