# Generated by Django 4.1.5 on 2023-03-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0079_rename_images_notifications_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='requesting_id_format',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
