# Generated by Django 4.1.5 on 2023-03-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0080_notifications_requesting_id_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='requested_response',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
