# Generated by Django 4.1.5 on 2023-03-17 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0074_alter_store_info_store_address2'),
        ('emercado', '0081_notifications_requested_response'),
    ]

    operations = [
    ]
