# Generated by Django 4.1.5 on 2023-03-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0082_merge_20230317_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='account_responded',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='account_responded_id_format',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='account_responded_name',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
