# Generated by Django 4.1.1 on 2023-03-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0083_notifications_account_responded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_info',
            name='store_address2',
            field=models.CharField(max_length=120),
        ),
    ]
