# Generated by Django 4.1.5 on 2023-03-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0083_notifications_account_responded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='shared_to',
            field=models.TextField(default='', null=True),
        ),
    ]
