# Generated by Django 4.1.5 on 2023-03-20 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0084_alter_orders_shared_to'),
        ('emercado', '0084_alter_store_info_store_address2'),
    ]

    operations = [
    ]
