# Generated by Django 4.1.5 on 2023-03-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0085_merge_20230320_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='read',
            field=models.IntegerField(default=0),
        ),
    ]
