# Generated by Django 4.1.5 on 2023-03-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0086_notifications_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='discounts_access',
            field=models.IntegerField(default=0),
        ),
    ]
