# Generated by Django 4.1.5 on 2023-03-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0087_role_discounts_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount_Personnel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_format', models.CharField(max_length=45)),
                ('personnel_status', models.CharField(max_length=120)),
                ('discount_percentage', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'emcdo_discount_personnel',
            },
        ),
    ]
