# Generated by Django 4.1.5 on 2023-03-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0089_orders_percentage_dicount_orders_personnel_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel_Discounts_Requests',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_format', models.CharField(max_length=45, null=True)),
                ('consumer_id', models.IntegerField(null=True)),
                ('consumer_id_format', models.CharField(max_length=45, null=True)),
                ('order_id', models.IntegerField(null=True)),
                ('order_id_format', models.CharField(max_length=45, null=True)),
                ('personnel_discount_id', models.IntegerField(null=True)),
                ('personnel_discount_id_format', models.CharField(max_length=45, null=True)),
                ('personnel_status', models.CharField(max_length=45, null=True)),
            ],
            options={
                'db_table': 'emcdo_personnel_discount_requests',
            },
        ),
        migrations.AddField(
            model_name='notifications',
            name='requesting_discount',
            field=models.IntegerField(null=True),
        ),
    ]
