# Generated by Django 4.1.5 on 2023-03-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0092_personnel_discount_requests_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel_discount_requests',
            name='store_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='personnel_discount_requests',
            name='store_id_format',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
