# Generated by Django 4.1.5 on 2023-03-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0093_personnel_discount_requests_store_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='personnel_discount_id',
            field=models.IntegerField(null=True),
        ),
    ]
