# Generated by Django 4.1.5 on 2023-03-25 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0094_orders_personnel_discount_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='personnel_discount',
            new_name='personnel_status',
        ),
    ]
