# Generated by Django 4.1.5 on 2023-03-25 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0095_rename_personnel_discount_orders_personnel_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='percentage_dicount',
            new_name='percentage_discount',
        ),
    ]
