# Generated by Django 4.1.5 on 2023-03-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0096_rename_percentage_dicount_orders_percentage_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='discounted_flag',
            field=models.IntegerField(default=0),
        ),
    ]
