# Generated by Django 4.1.5 on 2023-03-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0098_consumer_account_verification_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vouchers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_format', models.CharField(max_length=45, null=True)),
                ('voucher_name', models.CharField(max_length=120)),
                ('store_id', models.IntegerField(null=True)),
                ('store_id_format', models.CharField(max_length=45, null=True)),
                ('reward_type', models.CharField(max_length=45, null=True)),
                ('voucher_type', models.CharField(max_length=45)),
                ('discount_type', models.CharField(max_length=45)),
                ('discount_percentage', models.FloatField(null=True)),
                ('fix_amount_discount', models.FloatField(null=True)),
                ('minimum_spent', models.FloatField(null=True)),
                ('product_list', models.TextField(null=True)),
                ('date_start', models.DateField()),
                ('time_start', models.TimeField(null=True)),
                ('date_end', models.DateField()),
                ('time_end', models.TimeField(null=True)),
                ('status', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'emcdo_vouchers',
            },
        ),
    ]
