# Generated by Django 4.1.1 on 2023-03-29 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0099_store_info_latitude_store_info_longitude'),
        ('emercado', '0099_vouchers'),
    ]

    operations = [
    ]
