# Generated by Django 4.1.5 on 2023-03-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0099_vouchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='voucher_discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='total_usage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='usage_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
