# Generated by Django 4.1.5 on 2023-03-30 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0100_orders_voucher_discount_vouchers_total_usage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vouchers',
            old_name='minimum_spent',
            new_name='minimum_spend',
        ),
    ]
