# Generated by Django 4.1.1 on 2023-03-30 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0100_merge_20230330_0747'),
        ('emercado', '0100_orders_voucher_discount_vouchers_total_usage_and_more'),
    ]

    operations = [
    ]
