# Generated by Django 4.1.1 on 2023-03-30 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emercado', '0101_merge_20230330_1659'),
        ('emercado', '0101_rename_minimum_spent_vouchers_minimum_spend'),
    ]

    operations = [
    ]
