"""
Django settings for MAT project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b487s#itlpgfca-_2slq!2*dcag4musuowx(rc^gsaar(z524t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

URL_SITE_DOMAIN = "http://127.0.0.1:8000"
# URL_SITE_DOMAIN = "http://18.143.58.172"

# "test"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'emercado',
    'django_apscheduler',


    # 'widget_tweaks',
    # 'crispy_forms',
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MAT.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MAT.wsgi.application'


# AUTH_USER_MODEL = 'emercado.User'
# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases


# KATH
# DATABASES = {
#       'default': {
#           'ENGINE': 'django.db.backends.mysql',
#           'NAME': 'emercado',
#           'USER': 'root',
#           'PASSWORD': 'p@ssw0rd',
#           'PORT': 3306,
#           'HOST': '127.0.0.1'
#       }
# }


# KENT DATABASE
# DATABASES = {
#      'default': {
#          'ENGINE': 'django.db.backends.mysql',
#          'NAME': 'emercado',
#          'USER': 'root',
#          'PASSWORD': 'yjh434ctuG@-@',
#          'PORT': 3306,
#          'HOST': '127.0.0.1'
#      }
#  }


# LARA and RENA DATABASE
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'emercado',
#         'USER': 'root',
#         'PASSWORD': 'jazfer',
#         'PORT': 3307,
#         'HOST': '127.0.0.1'
#     }
# }


#JPreng & Piedra
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'emercado',
        'USER': 'root',
        'PASSWORD': 'graduatetracer',
        'PORT': 3307,
        'HOST': '127.0.0.1'
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/


STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'Post_Media')

MEDIA_URL = '/Post_Media/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

SESSION_EXPIRE_AT_BROWSER_CLOSE = False
#SESSION_SAVE_EVERY_REQUEST = True
MESSAGE_LEVEL = 10

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.office365.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'renzallera27@gmail.com'
EMAIL_HOST_PASSWORD = 'oidfteoamugikjnn'
# EMAIL_HOST_USER = 'support@dinnoxitsolutions.com'
# EMAIL_HOST_PASSWORD = 'Rac77793'
